name: md_bootstrap_scss
version: 4.1.3+0
description: Angular Bootstrap with Material Design Sass source (free version)
author: TLM <source@legionmarket.com>
homepage: https://github.com/Dart-Land/md_bootstrap_scss
environment:
  sdk: '2.1.1 < 3.0.0'
dev_dependencies:
  build_test: ^0.10.3+3
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4+2
  sass_builder: ^2.1.2
